export const FigureCategories = [
  'Class distribution',
  'Cross-validation',
  'Model comparison',
  'Test evaluation',
  'Deployment',
]

export const FigureModels = [
  'Decision Tree',
  'Random Forest',
  'Logistic Regression',
  'Naive Bayes',
  'Dummy (stratified)',
]

// All catalog figures depict the PRE-RETRAINING experiments (ML-EXP-001 /
// ML-EXP-002): they show the earlier pipeline's results and are superseded by
// the retrained numbers on the Evaluation page. Kept for reference only.
export const FigureStalenessNote = 'Figures from the pre-retraining experiments (ML-EXP-001 / ML-EXP-002) — they depict the earlier pipeline\u2019s results and are superseded by the retrained numbers on the Evaluation page.'

export const FigureCatalog = [
  {
    id: 'class-distribution',
    src: './figures/class_distribution.png',
    category: 'Class distribution',
    metric: 'Class balance',
    model: 'All models',
    label: 'Class balance — dataset distribution',
    experiment: '',
  },
  {
    id: 'cv-accuracy-comparison',
    src: './figures/cv/task5_cv_accuracy_comparison.png',
    category: 'Cross-validation',
    metric: 'Accuracy',
    model: 'All models',
    label: 'CV accuracy — 4 models',
    experiment: 'EXP-001',
  },
  {
    id: 'cv-f1-by-fold',
    src: './figures/cv/task5_cv_f1_by_fold.png',
    category: 'Cross-validation',
    metric: 'F1',
    model: 'All models',
    label: 'CV F1 by fold — 4 models',
    experiment: 'EXP-001',
  },
  {
    id: 'cv-f1-comparison',
    src: './figures/cv/task5_cv_f1_comparison.png',
    category: 'Cross-validation',
    metric: 'F1',
    model: 'All models',
    label: 'CV F1 — 4 models',
    experiment: 'EXP-001',
  },
  {
    id: 'cv-precision-comparison',
    src: './figures/cv/task5_cv_precision_comparison.png',
    category: 'Cross-validation',
    metric: 'Precision',
    model: 'All models',
    label: 'CV precision — 4 models',
    experiment: 'EXP-001',
  },
  {
    id: 'cv-recall-comparison',
    src: './figures/cv/task5_cv_recall_comparison.png',
    category: 'Cross-validation',
    metric: 'Recall',
    model: 'All models',
    label: 'CV recall — 4 models',
    experiment: 'EXP-001',
  },
  {
    id: 'cv-roc-auc-comparison',
    src: './figures/cv/task5_cv_roc_auc_comparison.png',
    category: 'Cross-validation',
    metric: 'ROC-AUC',
    model: 'All models',
    label: 'CV ROC-AUC — 4 models',
    experiment: 'EXP-001',
  },
  {
    id: 'model-comparison-cv-accuracy',
    src: './figures/model_comparison/model_comparison_cv_accuracy.png',
    category: 'Model comparison',
    metric: 'Accuracy',
    model: 'All models',
    label: 'Model comparison CV accuracy',
    experiment: 'EXP-001',
  },
  {
    id: 'model-comparison-cv-f1',
    src: './figures/model_comparison/model_comparison_cv_f1.png',
    category: 'Model comparison',
    metric: 'F1',
    model: 'All models',
    label: 'Model comparison CV F1',
    experiment: 'EXP-001',
  },
  {
    id: 'model-comparison-cv-precision',
    src: './figures/model_comparison/model_comparison_cv_precision.png',
    category: 'Model comparison',
    metric: 'Precision',
    model: 'All models',
    label: 'Model comparison CV precision',
    experiment: 'EXP-001',
  },
  {
    id: 'model-comparison-cv-recall',
    src: './figures/model_comparison/model_comparison_cv_recall.png',
    category: 'Model comparison',
    metric: 'Recall',
    model: 'All models',
    label: 'Model comparison CV recall',
    experiment: 'EXP-001',
  },
  {
    id: 'model-comparison-cv-roc-auc',
    src: './figures/model_comparison/model_comparison_cv_roc_auc.png',
    category: 'Model comparison',
    metric: 'ROC-AUC',
    model: 'All models',
    label: 'Model comparison CV ROC-AUC',
    experiment: 'EXP-001',
  },
  {
    id: 'exp1-cm-decision-tree',
    src: './figures/test_eval_exp1/test_cm_decision_tree.png',
    category: 'Test evaluation',
    metric: 'Confusion matrix',
    model: 'Decision Tree',
    label: 'Test confusion matrix — Decision Tree (EXP-001)',
    experiment: 'EXP-001',
  },
  {
    id: 'exp1-cm-logistic-regression',
    src: './figures/test_eval_exp1/test_cm_logistic_regression.png',
    category: 'Test evaluation',
    metric: 'Confusion matrix',
    model: 'Logistic Regression',
    label: 'Test confusion matrix — Logistic Regression (EXP-001)',
    experiment: 'EXP-001',
  },
  {
    id: 'exp1-cm-naive-bayes',
    src: './figures/test_eval_exp1/test_cm_naive_bayes.png',
    category: 'Test evaluation',
    metric: 'Confusion matrix',
    model: 'Naive Bayes',
    label: 'Test confusion matrix — Naive Bayes (EXP-001)',
    experiment: 'EXP-001',
  },
  {
    id: 'exp1-cm-random-forest',
    src: './figures/test_eval_exp1/test_cm_random_forest.png',
    category: 'Test evaluation',
    metric: 'Confusion matrix',
    model: 'Random Forest',
    label: 'Test confusion matrix — Random Forest (EXP-001)',
    experiment: 'EXP-001',
  },
  {
    id: 'exp1-pr-combined',
    src: './figures/test_eval_exp1/test_pr_combined.png',
    category: 'Test evaluation',
    metric: 'PR curve',
    model: 'All models',
    label: 'Test PR curve — all models (EXP-001)',
    experiment: 'EXP-001',
  },
  {
    id: 'exp1-roc-combined',
    src: './figures/test_eval_exp1/test_roc_combined.png',
    category: 'Test evaluation',
    metric: 'ROC curve',
    model: 'All models',
    label: 'Test ROC curve — all models (EXP-001)',
    experiment: 'EXP-001',
  },
  {
    id: 'exp1-tree-decision-tree',
    src: './figures/test_eval_exp1/test_tree_decision_tree.png',
    category: 'Test evaluation',
    metric: 'Tree structure',
    model: 'Decision Tree',
    label: 'Test tree structure — Decision Tree (EXP-001)',
    experiment: 'EXP-001',
  },
  {
    id: 'exp2-deployment-bands-per-model',
    src: './figures/test_eval_exp2/deployment_bands_per_model.png',
    category: 'Deployment',
    metric: 'Band distribution',
    model: 'All models',
    label: 'Deployment bands per model (EXP-002)',
    experiment: 'EXP-002',
  },
  {
    id: 'exp2-cm-decision-tree',
    src: './figures/test_eval_exp2/test_cm_decision_tree.png',
    category: 'Test evaluation',
    metric: 'Confusion matrix',
    model: 'Decision Tree',
    label: 'Test confusion matrix — Decision Tree (EXP-002)',
    experiment: 'EXP-002',
  },
  {
    id: 'exp2-cm-dummy-stratified',
    src: './figures/test_eval_exp2/test_cm_dummy_(stratified).png',
    category: 'Test evaluation',
    metric: 'Confusion matrix',
    model: 'Dummy (stratified)',
    label: 'Test confusion matrix — Dummy stratified (EXP-002)',
    experiment: 'EXP-002',
  },
  {
    id: 'exp2-cm-logistic-regression',
    src: './figures/test_eval_exp2/test_cm_logistic_regression.png',
    category: 'Test evaluation',
    metric: 'Confusion matrix',
    model: 'Logistic Regression',
    label: 'Test confusion matrix — Logistic Regression (EXP-002)',
    experiment: 'EXP-002',
  },
  {
    id: 'exp2-cm-naive-bayes',
    src: './figures/test_eval_exp2/test_cm_naive_bayes.png',
    category: 'Test evaluation',
    metric: 'Confusion matrix',
    model: 'Naive Bayes',
    label: 'Test confusion matrix — Naive Bayes (EXP-002)',
    experiment: 'EXP-002',
  },
  {
    id: 'exp2-cm-random-forest',
    src: './figures/test_eval_exp2/test_cm_random_forest.png',
    category: 'Test evaluation',
    metric: 'Confusion matrix',
    model: 'Random Forest',
    label: 'Test confusion matrix — Random Forest (EXP-002)',
    experiment: 'EXP-002',
  },
  {
    id: 'exp2-pr-combined',
    src: './figures/test_eval_exp2/test_pr_combined.png',
    category: 'Test evaluation',
    metric: 'PR curve',
    model: 'All models',
    label: 'Test PR curve — all models (EXP-002)',
    experiment: 'EXP-002',
  },
  {
    id: 'exp2-roc-combined',
    src: './figures/test_eval_exp2/test_roc_combined.png',
    category: 'Test evaluation',
    metric: 'ROC curve',
    model: 'All models',
    label: 'Test ROC curve — all models (EXP-002)',
    experiment: 'EXP-002',
  },
  {
    id: 'exp2-tree-decision-tree',
    src: './figures/test_eval_exp2/test_tree_decision_tree.png',
    category: 'Test evaluation',
    metric: 'Tree structure',
    model: 'Decision Tree',
    label: 'Test tree structure — Decision Tree (EXP-002)',
    experiment: 'EXP-002',
  },
]
